name: Generate Snake

on:
  schedule:
    - cron: "0 0 * * *"
  workflow_dispatch:
  push:
    branches: ["main"]

permissions:
  contents: write

jobs:
  generate:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Generate snake (light & dark)
        uses: Platane/snk@v3
        with:
          github_user_name: tekuper
          outputs: |
            assets/snake.svg
            assets/snake-dark.svg?palette=github-dark

      - name: Commit SVGs to main
        uses: EndBug/add-and-commit@v9
        with:
          add: "assets/*.svg"
          message: "chore: update snake svgs"
